blank_issues_enabled: false
contact_links:
  - name: Report duplication bugs and exploits
    url: https://github.com/PluginBugs/Issues-ItemsAdder/security/policy
    about: DO NOT REPORT DUPLICATION BUGS ON GITHUB!
  - name: Discord server
    url: https://discord.gg/lonedev-s-plugins-533407895010803753
    about: My personal Discord server
  - name: ItemsAdder wiki
    url: http://a.devs.beer/git-wiki-issue
    about: Official wiki of ItemsAdder
  - name: ItemsAdder Spigot page
    url: http://a.devs.beer/git-iaspigot-issue
    about: Official SpigotMC.org page of ItemsAdder
