blank_issues_enabled: false
contact_links:
  - name: Project Slack server
    url: https://smuguildhall.slack.com/archives/C07J98Y1Q8J
    about: Project Discord server
  - name: Project wiki
    url: https://smuguildhall.slack.com/archives/C07J98Y1Q8J
    about: Official wiki of Beaver Quest